services:
  _defaults:
    autowire: true
    autoconfigure: true

  Kibatic\DatagridBundle\Grid\GridBuilder:
    public: true

  Kibatic\DatagridBundle\Twig\HtmlExtension:
    public: true
    tags:
      - { name: twig.extension }

  Kibatic\DatagridBundle\Maker\MakeDatagrid:
    arguments:
      $entityHelper: '@maker.doctrine_helper'
      $generator: '@maker.generator'
    tags:
      - { name: maker.command }
