services:
  _defaults:
    autowire: true
    autoconfigure: true

  Kibatic\DatagridBundle\Grid\GridBuilder:
    public: true

  Kibatic\DatagridBundle\Twig\AppExtension:
    public: true
    tags:
      - { name: twig.extension }

  Kibatic\DatagridBundle\Maker\MakeDatagrid:
    arguments:
      $entityHelper: '@maker.doctrine_helper'
      $formTypeRenderer: '@maker.renderer.form_type_renderer'
    tags:
      - { name: maker.command }

  Kibatic\DatagridBundle\Twig\Components\DatagridComponent:
    tags:
        - twig.component: { key: 'datagrid', template: '@KibaticDatagrid/components/datagrid.html.twig' }

  Kibatic\DatagridBundle\Twig\Components\DatagridFiltersComponent:
    tags:
      - twig.component: { key: 'datagrid-filters', template: '@KibaticDatagrid/components/datagrid-filters.html.twig' }
